import type {CommerceChannelAdapter,ChannelHealth,ChannelOpportunity} from "./channel-adapters.js";
import type {PlatformDefinition} from "./platform-registry.js";
const API="https://api.dealwork.ai/api/v1";
const clean=(v:unknown,max=12000)=>String(v??"").replace(/<[^>]+>/g," ").replace(/[\u0000-\u001f]+/g," ").replace(/\s+/g," ").trim().slice(0,max);
export class DealWorkAdapter implements CommerceChannelAdapter{
 constructor(readonly platform:PlatformDefinition,private readonly env:NodeJS.ProcessEnv=process.env,private readonly fetcher:typeof fetch=fetch){}
 private headers():Record<string,string>{const headers:Record<string,string>={accept:"application/json"};const key=this.env.AUTOMATON_DEALWORK_API_KEY;if(key)headers.authorization=`Bearer ${key}`;return headers;}
 async health():Promise<ChannelHealth>{const ready=Boolean(this.env.AUTOMATON_DEALWORK_API_KEY&&this.env.AUTOMATON_DEALWORK_AGENT_ID);return{platformId:this.platform.id,ready,mode:"api",reason:ready?undefined:"missing DealWork agent credentials"};}
 async discover():Promise<{opportunities:ChannelOpportunity[]}>{
  const response=await this.fetcher(`${API}/jobs`,{headers:{accept:"application/json","user-agent":"OakhamptonAutomaton/0.3 (+https://www.oakhampton.ai/automation-services/)"},signal:AbortSignal.timeout(15000)});if(response.status===429)throw new Error("DEALWORK_RATE_LIMITED");if(!response.ok)throw new Error(`DEALWORK_API_ERROR:${response.status}`);
  const payload:any=await response.json(),rows=Array.isArray(payload?.data)?payload.data:[];
  const opportunities=rows.map((row:any):ChannelOpportunity|null=>{const id=clean(row.id,160),title=clean(row.title,240),status=clean(row.status,40);if(!id||!title||!['open','bidding'].includes(status)||row.posterFunded!==true||row.eligibleWorkerTypes==='human_only')return null;const budget=Number(row.fixedPrice??row.budgetMax??row.budgetMin??0),criteria=Array.isArray(row.acceptanceCriteria)?row.acceptanceCriteria.map((c:any)=>clean(c?.description??c,240)).filter(Boolean):[];return{platformId:'dealwork',sourceId:id,url:`https://dealwork.ai/jobs/${encodeURIComponent(id)}`,language:clean(row.originalLanguage,16)||'en',title,body:clean(row.description),budgetCents:Number.isFinite(budget)?Math.max(0,Math.round(budget*100)):0,currency:'USD',metadata:{category:clean(row.category,120),tags:Array.isArray(row.tags)?row.tags:[],acceptanceCriteria:criteria,eligibleWorkerTypes:clean(row.eligibleWorkerTypes,40),jobMode:clean(row.jobMode,40),deadline:clean(row.deadline,80),biddingDeadline:clean(row.biddingDeadline,80),bidCount:Number(row.bidCount??0),posterFunded:true,posterTrustTierLevel:Number(row.posterTrustTierLevel??0),company:clean(row.posterDisplayName,240),discoveredVia:'official_public_api'}};}).filter((x:ChannelOpportunity|null):x is ChannelOpportunity=>Boolean(x));return{opportunities};
 }
 async fetchMessages(cursor?:string){const key=this.env.AUTOMATON_DEALWORK_API_KEY;if(!key)return{messages:[],cursor};const response=await this.fetcher(`${API}/notifications`,{headers:this.headers(),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`DEALWORK_NOTIFICATIONS_ERROR:${response.status}`);const payload:any=await response.json(),rows=Array.isArray(payload?.data)?payload.data:Array.isArray(payload?.notifications)?payload.notifications:[];const newer=cursor?rows.filter((r:any)=>String(r.createdAt??r.created_at??'')>cursor):rows;const messages=newer.map((r:any)=>({id:String(r.id),customerId:String(r.accountId??r.senderId??'dealwork'),subject:clean(r.title??r.type,180),body:clean(r.message??r.body??JSON.stringify(r.data??{})),from:'notifications@dealwork.ai',to:[],threadId:String(r.contractId??r.jobId??r.id),receivedAt:String(r.createdAt??r.created_at??''),attachments:[]}));const next=messages.reduce((latest:any,m:any)=>m.receivedAt>latest?m.receivedAt:latest,cursor??'');return{messages,cursor:next||cursor};}
 async submitApprovedAction(input:{type:string;payload:Record<string,unknown>;idempotencyKey:string}):Promise<{externalId:string;status:string}>{if(input.type!=='submit_proposal')throw new Error(`DEALWORK_ACTION_UNSUPPORTED:${input.type}`);if(!(await this.health()).ready)throw new Error('DEALWORK_CREDENTIALS_MISSING');const p:any=input.payload,proposal:any=p.proposal??{},jobId=String(proposal.sourceId??p.sourceId??'');if(!jobId)throw new Error('DEALWORK_JOB_ID_MISSING');const response=await this.fetcher(`${API}/jobs/${encodeURIComponent(jobId)}/bids`,{method:'POST',headers:{...this.headers(),'content-type':'application/json','idempotency-key':input.idempotencyKey},body:JSON.stringify({jobId,amount:Number(proposal.priceCents??p.amountCents??0)/100,message:String(proposal.body??'')}),signal:AbortSignal.timeout(15000)});if(response.status===409)return{externalId:`dealwork:${jobId}`,status:'duplicate'};const body:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`DEALWORK_BID_ERROR:${response.status}:${clean(body?.error?.message??body?.message,240)}`);const data=body.data??body;return{externalId:String(data.id??data.bidId??`dealwork:${jobId}`),status:String(data.status??'submitted')};}
}
