import type {CommerceChannelAdapter,ChannelHealth,ChannelOpportunity} from "./channel-adapters.js";
import type {PlatformDefinition} from "./platform-registry.js";
const API="https://www.freelancer.com/api";
const clean=(v:unknown,max=12000)=>String(v??"").replace(/<[^>]+>/g," ").replace(/[\u0000-\u001f]+/g," ").replace(/\s+/g," ").trim().slice(0,max);
const hints=(text:string)=>{const groups:[RegExp,string][]=[[/\b(api|automatizaci[oó]n|automação|automatisation|automatisierung|自動化|integraci[oó]n|integração|intégration|entwicklung|desarrollo|desenvolvimento|développement|python|typescript|javascript|docker|devops|n8n|zapier)\b/iu,'api automation integration software python typescript developer workflow'],[/\b(investigaci[oó]n|pesquisa|recherche|forschung|調査|an[aá]lisis|análise|analyse|分析|informe|relat[oó]rio|rapport|bericht|レポート)\b/iu,'research analysis report brief'],[/\b(datos|dados|données|daten|データ|excel|hoja de c[aá]lculo|planilha|tableur|tabelle|スプレッドシート|sql|dashboard)\b/iu,'data spreadsheet excel sql dashboard database'],[/\b(sitio web|website|site web|webseite|ウェブサイト|landing page|wordpress|shopify|ecommerce|portal)\b/iu,'website landing page frontend portal'],[/\b(documentaci[oó]n|documentação|documentation|dokumentation|文書|presentaci[oó]n|apresentação|présentation|präsentation|提案書)\b/iu,'document proposal presentation documentation content system']];return groups.filter(([r])=>r.test(text)).map(([,h])=>h).join(' ');};
export class FreelancerApiAdapter implements CommerceChannelAdapter{
 constructor(readonly platform:PlatformDefinition,private readonly env:NodeJS.ProcessEnv=process.env,private readonly fetcher:typeof fetch=fetch){}
 async health():Promise<ChannelHealth>{return{platformId:this.platform.id,ready:true,mode:'api',reason:this.env.AUTOMATON_FREELANCER_OAUTH_TOKEN?undefined:'public discovery only; missing AUTOMATON_FREELANCER_OAUTH_TOKEN'};}
 async discover():Promise<{opportunities:ChannelOpportunity[]}>{const url=`${API}/projects/0.1/projects/active/?limit=100&full_description=true&compact=false`;const response=await this.fetcher(url,{headers:{accept:'application/json','user-agent':'OakhamptonAutomaton/0.3 (+https://www.oakhampton.ai/automation-services/)'},signal:AbortSignal.timeout(20000)});if(response.status===429)throw new Error('FREELANCER_RATE_LIMITED');if(!response.ok)throw new Error(`FREELANCER_API_ERROR:${response.status}`);const payload:any=await response.json(),rows=Array.isArray(payload?.result?.projects)?payload.result.projects:[];const opportunities=rows.map((row:any):ChannelOpportunity|null=>{const id=String(row.id??''),title=clean(row.title,240),currency=clean(row.currency?.code,8);if(!id||!title||row.status!=='active'||row.nonpublic||row.local||row.hireme||!currency)return null;const maximum=Number(row.budget?.maximum??row.budget?.minimum??0),description=clean(row.description??row.preview_description),language=clean(row.language??'en',12).toLowerCase();return{platformId:'freelancer',sourceId:id,url:`https://www.freelancer.com/projects/${clean(row.seo_url,500)}`,language,title,body:description,budgetCents:Number.isFinite(maximum)?Math.max(0,Math.round(maximum*100)):0,currency,metadata:{tags:[],classificationHints:hints(`${title} ${description}`),projectType:clean(row.type,30),budgetMin:row.budget?.minimum,budgetMax:row.budget?.maximum,bidCount:Number(row.bid_stats?.bid_count??0),bidAverage:row.bid_stats?.bid_avg,escrowSupported:Boolean(row.currency?.is_escrowcom_supported),sellerKycRequired:Boolean(row.is_seller_kyc_required),buyerKycRequired:Boolean(row.is_buyer_kyc_required),originalLanguage:language,discoveredVia:'official_public_api',acceptanceCriteria:description?[`Deliver the requirements stated in the project description`]:[]}};}).filter((x:ChannelOpportunity|null):x is ChannelOpportunity=>Boolean(x));return{opportunities};}
 async fetchMessages(cursor?:string){return{messages:[],cursor};}
 private async bidderId(token:string){if(this.env.AUTOMATON_FREELANCER_USER_ID)return Number(this.env.AUTOMATON_FREELANCER_USER_ID);const r=await this.fetcher(`${API}/users/0.1/self/`,{headers:{accept:'application/json','freelancer-oauth-v1':token},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`FREELANCER_SELF_ERROR:${r.status}`);const b:any=await r.json();const id=Number(b?.result?.id);if(!Number.isSafeInteger(id))throw new Error('FREELANCER_USER_ID_MISSING');return id;}
 async submitApprovedAction(input:{type:string;payload:Record<string,unknown>;idempotencyKey:string}):Promise<{externalId:string;status:string}>{if(input.type!=='submit_proposal')throw new Error(`FREELANCER_ACTION_UNSUPPORTED:${input.type}`);const token=this.env.AUTOMATON_FREELANCER_OAUTH_TOKEN;if(!token)throw new Error('FREELANCER_OAUTH_TOKEN_MISSING');const p:any=input.payload,proposal:any=p.proposal??{},projectId=Number(proposal.sourceId??p.sourceId);if(!Number.isSafeInteger(projectId))throw new Error('FREELANCER_PROJECT_ID_MISSING');const bidderId=await this.bidderId(token);const response=await this.fetcher(`${API}/projects/0.1/bids/`,{method:'POST',headers:{accept:'application/json','content-type':'application/json','freelancer-oauth-v1':token,'idempotency-key':input.idempotencyKey},body:JSON.stringify({project_id:projectId,bidder_id:bidderId,description:String(proposal.body??''),amount:Number(proposal.priceCents??p.amountCents??0)/100,period:7,milestone_percentage:100}),signal:AbortSignal.timeout(15000)});const body:any=await response.json().catch(()=>({}));if(response.status===409)return{externalId:`freelancer:${projectId}`,status:'duplicate'};if(!response.ok)throw new Error(`FREELANCER_BID_ERROR:${response.status}:${clean(body?.message??body?.error_code,240)}`);return{externalId:String(body?.result?.id??`freelancer:${projectId}`),status:'submitted'};}
}
