export type CustomerStage="lead"|"qualified"|"quoted"|"contracted"|"delivering"|"completed"|"settled"|"suppressed";
export interface CustomerRecord { id:string; platformId:string; language:string; stage:CustomerStage; agreedScope?:string; priceCents?:number; currency?:string; revisionCount:number; settlementEventId?:string; }
export class CustomerCRM { private readonly records=new Map<string,CustomerRecord>(); upsert(record:CustomerRecord){this.records.set(record.id,{...record});} get(id:string){const r=this.records.get(id);return r?{...r}:undefined;} transition(id:string,stage:CustomerStage){const r=this.records.get(id);if(!r)throw new Error("unknown customer");if(r.stage==="suppressed"&&stage!=="suppressed")throw new Error("suppressed customer");r.stage=stage;} list(){return [...this.records.values()].map(x=>({...x}));} }
export interface FulfilmentHarness { id:string; requiredInputs:string[]; acceptanceEvidence:string[]; maximumRevisions:number; }
export class FulfilmentRegistry { private readonly items=new Map<string,FulfilmentHarness>(); register(h:FulfilmentHarness){if(this.items.has(h.id))throw new Error("duplicate harness");this.items.set(h.id,{...h});} get(id:string){const h=this.items.get(id);if(!h)throw new Error("unknown harness");return {...h};} }
export interface CapacityState { activeOrders:number; queueDepth:number; workers:number; settledProfitCents:number; refundRateBps:number; complaintRateBps:number; }
export interface CapacityPolicy { maximumOrdersPerWorker:number; queueDepthPerNewWorker:number; minimumProfitPerNewWorkerCents:number; maximumRefundRateBps:number; maximumComplaintRateBps:number; maximumWorkers:number; }
export function capacityDecision(s:CapacityState,p:CapacityPolicy):"pause"|"hold"|"spawn" {
  if(s.refundRateBps>p.maximumRefundRateBps||s.complaintRateBps>p.maximumComplaintRateBps||s.activeOrders>s.workers*p.maximumOrdersPerWorker) return "pause";
  if(s.workers<p.maximumWorkers&&s.queueDepth>=p.queueDepthPerNewWorker&&s.settledProfitCents>=p.minimumProfitPerNewWorkerCents) return "spawn"; return "hold";
}
export interface Settlement { eventId:string; grossCents:number; refundsCents:number; chargebacksCents:number; platformFeesCents:number; acquisitionCents:number; fulfilmentCents:number; currency:string; settled:boolean; }
export class SettlementLedger { private readonly events=new Map<string,Settlement>(); record(s:Settlement){if(this.events.has(s.eventId))throw new Error("duplicate settlement");if(!s.settled)throw new Error("unsettled revenue");this.events.set(s.eventId,{...s});return s.grossCents-s.refundsCents-s.chargebacksCents-s.platformFeesCents-s.acquisitionCents-s.fulfilmentCents;} totalNet(){return [...this.events.values()].reduce((n,s)=>n+s.grossCents-s.refundsCents-s.chargebacksCents-s.platformFeesCents-s.acquisitionCents-s.fulfilmentCents,0);} }
