import type { ChannelOpportunity } from "./channel-adapters.js";
import type { ProductionQualification } from "../quality/production.js";
import {buildBidStrategy,renderSpecificOpening} from "./bid-strategy.js";
export interface ProposalDraft { version:number; sourceUrl:string; platformId:string; sourceId:string; subject:string; body:string; priceCents:number; currency:string; assumptions:string[]; questions:string[]; acceptance:string[]; attribution?:{text:string;url:string}; }
export interface ProposalCritique { scoreBps:number; passed:boolean; failures:string[]; strengths:string[]; revisionRequired:boolean; }
const clean=(v:unknown,max=500)=>String(v??"").replace(/[\u0000-\u001f]+/g," ").replace(/\s+/g," ").trim().slice(0,max);
export function draftProposal(o:ChannelOpportunity,q:ProductionQualification):ProposalDraft {
 if(!q.eligible||!q.skillId||!q.routing)throw new Error("OPPORTUNITY_NOT_QUALITY_QUALIFIED");
 const strategy=buildBidStrategy(o,q);if(strategy.route==="decline")throw new Error("OPPORTUNITY_DECLINED_BY_BID_STRATEGY");
 const criteria=Array.isArray(o.metadata.acceptanceCriteria)?o.metadata.acceptanceCriteria.map(x=>clean(x,180)).filter(Boolean):[];
 const acceptance=criteria.length?criteria:["Agree a written deliverable checklist before work begins","Validate the completed work against that checklist"];
 const questions=["What exact output format and delivery environment should be used?","Can you provide a redacted representative input or example?","Which acceptance tests determine completion?"].slice(0,Math.max(1,3-strategy.clientSignals.length));
 const scope=clean(o.title,160),method=q.skillId==="software"?"I will reproduce the requirement, implement the smallest maintainable solution, add tests, and provide concise handover notes.":q.skillId==="research"?"I will define the questions, use attributable sources, separate evidence from inference, and deliver an editable report.":"I will confirm the inputs and target output, produce the deliverable, validate it against agreed checks, and include handover notes.";
 const routingNote=strategy.route==="autonomous"?"This fits our tested autonomous delivery loop, so I can price it competitively without reducing QA.":strategy.route==="openclaw"?"This is large enough to route through our OpenClaw delivery workspace with specialist review.":"The scope warrants direct senior oversight, which will be included in delivery.";
 const body=["Hello -- "+renderSpecificOpening(o,strategy),"Relevant fit: "+strategy.matchedCapabilities.join(", ")+".",method,routingNote,"Proposed fixed-scope budget: "+o.currency+" "+(strategy.bidPriceCents/100).toFixed(2)+". I will confirm scope and acceptance checks before starting.","Initial acceptance: "+acceptance.join("; ")+".",questions.length?"Focused questions: "+questions.join(" "):"The post already provides enough detail for an initial delivery plan.","AI-assisted work will be reviewed and validated before delivery. No external access, purchase, or deployment will occur without the required authorization."].join("\n\n");
 const attribution=o.metadata.attributionRequired?{text:clean(o.metadata.attributionText,80),url:o.url}:undefined;
 return {version:1,sourceUrl:o.url,platformId:o.platformId,sourceId:o.sourceId,subject:"Proposal: "+scope,body,priceCents:strategy.bidPriceCents,currency:o.currency,assumptions:["Fixed scope","Customer supplies lawful access and redacted examples","One consolidated revision round","Delivery route: "+strategy.route],questions,acceptance,attribution};
}
export function critiqueProposal(p:ProposalDraft,o:ChannelOpportunity,q:ProductionQualification):ProposalCritique {
 const expected=buildBidStrategy(o,q),failures:string[]=[],strengths:string[]=[];if(p.sourceUrl!==o.url)failures.push("SOURCE_URL_CHANGED");if(p.priceCents!==expected.bidPriceCents||p.currency!==o.currency)failures.push("COMMERCIAL_TERMS_CHANGED");if(p.acceptance.length===0)failures.push("ACCEPTANCE_MISSING");else strengths.push("TESTABLE_ACCEPTANCE");if(!p.body.includes("reviewed and validated"))failures.push("QUALITY_ASSURANCE_UNSTATED");else strengths.push("QUALITY_ASSURANCE_STATED");if(!p.body.includes("without the required authorization"))failures.push("AUTHORITY_BOUNDARY_MISSING");else strengths.push("AUTHORITY_BOUNDARY_STATED");if(!p.body.includes("You specifically need"))failures.push("CLIENT_SPECIFIC_OPENING_MISSING");else strengths.push("CLIENT_SPECIFIC_OPENING");if(p.body.length<300)failures.push("INSUFFICIENT_SPECIFICITY");if(p.body.length>3000)failures.push("EXCESSIVE_LENGTH");if(/guarantee|perfect|100%|best in the world/i.test(p.body))failures.push("UNSUPPORTED_CLAIM");if(q.routing?.requiresCritic)strengths.push("PREMIUM_CRITIC_ROUTE");if(o.metadata.attributionRequired&&(!p.attribution||p.attribution.url!==o.url))failures.push("ATTRIBUTION_MISSING_OR_CHANGED");const checks=9+(o.metadata.attributionRequired?1:0),scoreBps=Math.max(0,10000-Math.ceil(failures.length*10000/checks));return {scoreBps,passed:failures.length===0&&scoreBps>=9500,failures,strengths,revisionRequired:failures.length>0};
}
export function reviseProposal(p:ProposalDraft,critique:ProposalCritique,o:ChannelOpportunity,q?:ProductionQualification):ProposalDraft {
 let body=p.body;if(critique.failures.includes("QUALITY_ASSURANCE_UNSTATED"))body+="\n\nAll AI-assisted work will be reviewed and validated before delivery.";if(critique.failures.includes("AUTHORITY_BOUNDARY_MISSING"))body+="\n\nNo external action will occur without the required authorization.";if(critique.failures.includes("CLIENT_SPECIFIC_OPENING_MISSING"))body="Hello -- You specifically need "+clean(o.title,180)+".\n\n"+body;const price=q?buildBidStrategy(o,q).bidPriceCents:p.priceCents;return {...p,version:p.version+1,sourceUrl:o.url,priceCents:price,currency:o.currency,body,attribution:o.metadata.attributionRequired?{text:clean(o.metadata.attributionText,80),url:o.url}:p.attribution};
}
