import {estimateEconomics,evaluateOpportunity,normalizeOpportunity,type CapabilityProfile,type CommercePolicy,type RawOpportunity} from "./engine.js";
import {PlatformRegistry} from "./platform-registry.js";
export type ScenarioExpectation="propose"|"review"|"reject"|"error";
export interface SyntheticScenario { id:string; raw:RawOpportunity; translation:{title:string;body:string;confidenceBps:number}; costs:{acquisition:number;delivery:number;model:number;revisionBps:number;refundBps:number}; successProbabilityBps:number; expected:ScenarioExpectation; }
export interface ScenarioReport { total:number;correct:number;falseAccepts:number;falseRejects:number;errorsExpected:number;errorsUnexpected:number;accuracy:number;byDecision:Record<ScenarioExpectation,number>;failures:Array<{id:string;expected:ScenarioExpectation;actual:ScenarioExpectation;reasons:string[]}>; }
class Rng{constructor(private state:number){}next(){this.state=(this.state*1664525+1013904223)>>>0;return this.state/4294967296}int(a:number,b:number){return Math.floor(this.next()*(b-a+1))+a}pick<T>(x:T[]):T{return x[this.int(0,x.length-1)]}}
const base=(id:string):RawOpportunity=>({platformId:"upwork",sourceId:id,url:`https://example.test/jobs/${id}`,language:"en",title:"Automate a recurring report",body:"Normalize CSV files and generate a validated report",budgetCents:30000,currency:"USD",clientPaymentVerified:true,clientRatingBps:9000,proposalCount:5,requiredSkills:["excel","automation"],acceptanceCriteria:["fixture totals reconcile"]});
export function extremeScenarios():SyntheticScenario[]{const s=(id:string,raw:Partial<RawOpportunity>,expected:ScenarioExpectation,costs:Partial<SyntheticScenario["costs"]>={},confidence=9500,success=8500):SyntheticScenario=>({id,raw:{...base(id),...raw},translation:{title:"Translated",body:"Translated body",confidenceBps:confidence},costs:{acquisition:500,delivery:5000,model:1000,revisionBps:500,refundBps:500,...costs},successProbabilityBps:success,expected});return[
s("golden",{},"propose"),s("zero-budget",{budgetCents:0},"reject"),s("one-cent",{budgetCents:1},"reject"),s("unverified",{clientPaymentVerified:false},"reject"),s("proposal-flood",{proposalCount:1000000},"reject"),s("no-criteria",{acceptanceCriteria:[]},"reject"),s("no-skills",{requiredSkills:[]},"reject"),s("wrong-skills",{requiredSkills:["quantum-hardware"]},"reject"),s("uncertain-translation",{},"review",{},1000),s("unsupported-currency",{currency:"BTC"},"reject"),s("unsupported-language",{language:"ja"},"reject"),s("expired",{deadline:"2020-01-01T00:00:00Z"},"reject"),s("huge-delivery",{},"reject",{delivery:999999999}),s("negative-acquisition",{},"error",{acquisition:-1}),s("nan-model",{},"error",{model:Number.NaN}),s("success-overflow",{},"error",{},9500,10001),s("negative-success",{},"error",{},9500,-1),s("http-source",{url:"http://example.test"},"error"),s("negative-budget",{budgetCents:-1},"error")];}
export function generatedScenarios(count=1000,seed=42):SyntheticScenario[]{const r=new Rng(seed),out:SyntheticScenario[]=[];for(let i=0;i<count;i++){const valid=r.next()<.35,id=`generated-${i}`,raw=base(id);let expected:ScenarioExpectation="propose";const costs={acquisition:r.int(0,1500),delivery:r.int(1000,8000),model:r.int(100,2000),revisionBps:r.int(0,1000),refundBps:r.int(0,1000)};let confidence=r.int(8000,10000);if(!valid){const f=r.pick(["payment","competition","skills","criteria","translation","currency","loss"]);expected=f==="translation"?"review":"reject";if(f==="payment")raw.clientPaymentVerified=false;if(f==="competition")raw.proposalCount=100;if(f==="skills")raw.requiredSkills=["unsupported-skill"];if(f==="criteria")raw.acceptanceCriteria=[];if(f==="translation")confidence=3000;if(f==="currency")raw.currency="XYZ";if(f==="loss")costs.delivery=50000}out.push({id,raw,translation:{title:raw.title,body:raw.body,confidenceBps:confidence},costs,successProbabilityBps:r.int(7500,9500),expected})}return out;}
export function runSyntheticScenarios(xs:SyntheticScenario[],profile:CapabilityProfile,policy:CommercePolicy,registry=new PlatformRegistry()):ScenarioReport{let correct=0,falseAccepts=0,falseRejects=0,errorsExpected=0,errorsUnexpected=0;const byDecision={propose:0,review:0,reject:0,error:0};const failures:ScenarioReport["failures"]=[];for(const x of xs){let actual:ScenarioExpectation="error",reasons:string[]=[];try{const o=normalizeOpportunity(x.raw,x.translation),e=estimateEconomics(o,registry.get(o.platformId),x.costs,x.successProbabilityBps),d=evaluateOpportunity(o,registry.get(o.platformId),profile,e,policy);actual=d.decision;reasons=d.reasons}catch(err){reasons=[err instanceof Error?err.message:String(err)]}byDecision[actual]++;if(actual===x.expected){correct++;if(actual==="error")errorsExpected++}else{if(actual==="error")errorsUnexpected++;if(actual==="propose"&&x.expected!=="propose")falseAccepts++;if(actual!=="propose"&&x.expected==="propose")falseRejects++;failures.push({id:x.id,expected:x.expected,actual,reasons})}}return{total:xs.length,correct,falseAccepts,falseRejects,errorsExpected,errorsUnexpected,accuracy:xs.length?correct/xs.length:0,byDecision,failures};}
