import type {ChannelHealth,ChannelOpportunity,CommerceChannelAdapter} from "./channel-adapters.js";
import type {PlatformDefinition} from "./platform-registry.js";
type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;type R=Record<string,unknown>;
const arr=(v:unknown):R[]=>{if(Array.isArray(v))return v.filter((x):x is R=>!!x&&typeof x==="object");if(v&&typeof v==="object")for(const k of ["listings","data","items"]){const x=(v as R)[k];if(Array.isArray(x))return arr(x)}return[]};
const txt=(r:R,...ks:string[])=>{for(const k of ks){const v=r[k];if(typeof v==="string"&&v.trim())return v.trim()}return""};
const num=(r:R,...ks:string[])=>{for(const k of ks){const v=r[k];if(typeof v==="number"&&Number.isFinite(v))return v;if(typeof v==="string"&&/^\d+(?:\.\d+)?$/.test(v))return Number(v)}return 0};
export class SuperteamEarnAdapter implements CommerceChannelAdapter{
constructor(readonly platform:PlatformDefinition,private readonly env:NodeJS.ProcessEnv=process.env,private readonly fetcher:FetchLike=fetch){}
private get key(){return this.env.AUTOMATON_SUPERTEAM_EARN_API_KEY??""} private get base(){return(this.env.AUTOMATON_SUPERTEAM_EARN_BASE_URL??"https://superteam.fun").replace(/\/$/,"")}
async health():Promise<ChannelHealth>{return{platformId:this.platform.id,ready:!!this.key,mode:"api",reason:this.key?undefined:"missing AUTOMATON_SUPERTEAM_EARN_API_KEY"}}
async discover(cursor?:string):Promise<{opportunities:ChannelOpportunity[];cursor?:string}>{if(!this.key)return{opportunities:[]};const skip=Math.max(0,Number(cursor??0)||0),u=new URL(this.base+"/api/agents/listings/live");u.searchParams.set("take","50");u.searchParams.set("skip",String(skip));const res=await this.fetcher(u,{headers:{authorization:"Bearer "+this.key,accept:"application/json"}});if(!res.ok)throw new Error("SUPERTEAM_DISCOVERY_"+res.status);const items=arr(await res.json()),opportunities=items.filter(r=>["AGENT_ALLOWED","AGENT_ONLY"].includes(txt(r,"agentAccess","agent_access"))).filter(r=>{const d=txt(r,"deadline","endsAt");return !d||Number.isNaN(Date.parse(d))||Date.parse(d)>Date.now()}).map((r,i)=>{const slug=txt(r,"slug"),type=txt(r,"type","listingType").toLowerCase()||"bounty",direct=num(r,"rewardCents","budgetCents");return{platformId:this.platform.id,sourceId:txt(r,"id","listingId")||slug||String(skip+i),url:txt(r,"url","applyUrl")||this.base+"/earn/listing/"+slug+"/",language:"en",title:txt(r,"title","name")||"Untitled Superteam opportunity",body:[txt(r,"description","summary"),"Engagement: "+type,"Agent access: "+txt(r,"agentAccess","agent_access")].filter(Boolean).join("\n"),budgetCents:Math.round(direct||num(r,"rewardAmount","reward","amount","compensation","prize")*100),currency:txt(r,"currency","token")||"USDC",metadata:{listingType:type,agentAccess:txt(r,"agentAccess","agent_access"),deadline:txt(r,"deadline","endsAt"),raw:r}}});return{opportunities,cursor:items.length===50?String(skip+items.length):undefined}}
async fetchMessages(){return{messages:[]}}
async submitApprovedAction(input:{type:string;payload:Record<string,unknown>;idempotencyKey:string}){if(!this.env.AUTOMATON_ALLOW_EXTERNAL_EFFECTS)throw new Error("EXTERNAL_EFFECTS_DISABLED");if(!["submit","submit_proposal"].includes(input.type))throw new Error("SUPERTEAM_UNSUPPORTED_ACTION");const p:any=input.payload,proposal:any=p.proposal??{},listingId=String(proposal.sourceId??p.sourceId??"");if(!listingId)throw new Error("SUPERTEAM_LISTING_ID_MISSING");const body={listingId,proposal:String(proposal.body??""),amount:Number(proposal.priceCents??p.amountCents??0)/100,currency:String(proposal.currency??p.currency??"USDC"),portfolioUrl:"https://www.oakhampton.ai/automation-services/"};const res=await this.fetcher(this.base+"/api/agents/submissions/create",{method:"POST",headers:{authorization:"Bearer "+this.key,"content-type":"application/json","idempotency-key":input.idempotencyKey},body:JSON.stringify(body)});if(!res.ok)throw new Error("SUPERTEAM_SUBMISSION_"+res.status);const b=await res.json() as R;return{externalId:txt(b,"id","submissionId")||input.idempotencyKey,status:txt(b,"status")||"submitted"}}
}
