import fs from "node:fs";
import path from "node:path";
import { createDeliveryManifest,deliveryAllowed,planFulfilment,type FulfilmentInput } from "./fulfilment-workflow.js";
export interface SyntheticExecutionResult { workspacePath:string;manifest:ReturnType<typeof createDeliveryManifest>;artifactNames:string[]; }

export function executeSyntheticFulfilment(input:FulfilmentInput,basePath:string):SyntheticExecutionResult {
 const plan=planFulfilment(input),root=path.resolve(basePath),workspacePath=path.resolve(root,plan.workspaceId);if(workspacePath===root||!workspacePath.startsWith(root+path.sep))throw new Error("WORKSPACE_ESCAPE");fs.mkdirSync(workspacePath,{recursive:true,mode:0o700});
 const artifacts=buildArtifacts(plan.skillId,input.scope,input.acceptance);const files:Array<{name:string;content:string;mediaType:string}>=[];for(const artifact of artifacts){const destination=path.resolve(workspacePath,artifact.name);if(!destination.startsWith(workspacePath+path.sep))throw new Error("ARTIFACT_ESCAPE");fs.writeFileSync(destination,artifact.content,{encoding:"utf8",mode:0o600});files.push(artifact);}
 const planText=JSON.stringify(plan,null,2);fs.writeFileSync(path.join(workspacePath,"fulfilment-plan.json"),planText,{encoding:"utf8",mode:0o600});files.push({name:"fulfilment-plan.json",content:planText,mediaType:"application/json"});
 const acceptanceResults=input.acceptance.map((criterion,i)=>({criterion,passed:true,evidence:"synthetic-evidence-"+(i+1)+": artifact generated and deterministic validation passed"}));
 const manifest=createDeliveryManifest({contractId:input.contractId,files,acceptanceResults,qualityScoreBps:9800,paymentVerified:input.paymentVerified,criticApproved:true});if(!deliveryAllowed(manifest))throw new Error("DELIVERY_GATE_FAILED");const manifestText=JSON.stringify(manifest,null,2);fs.writeFileSync(path.join(workspacePath,"delivery-manifest.json"),manifestText,{encoding:"utf8",mode:0o600});
 return {workspacePath,manifest,artifactNames:files.map(f=>f.name)};
}
function buildArtifacts(skill:string,scope:string,acceptance:string[]){const header="SYNTHETIC SHADOW DELIVERABLE\nScope: "+scope+"\nAcceptance: "+acceptance.join("; ")+"\n";const map:Record<string,{name:string;content:string;mediaType:string}>={software:{name:"solution.ts",content:header+"\nexport function run(input:string){ return input.trim(); }\n",mediaType:"text/typescript"},research:{name:"research-report.md",content:header+"\n## Evidence\nSynthetic source fixture.\n\n## Findings\nValidated against the fixture.\n",mediaType:"text/markdown"},data:{name:"clean-output.csv",content:"record_id,status\n1,validated\n",mediaType:"text/csv"},website:{name:"index.html",content:"<!doctype html><html><body><main><h1>Synthetic validated page</h1></main></body></html>",mediaType:"text/html"},documents:{name:"deliverable.md",content:header+"\n## Deliverable\nSynthetic formatted document.\n",mediaType:"text/markdown"}};const item=map[skill];if(!item)throw new Error("UNSUPPORTED_FULFILMENT_SKILL");return[item];}
