import {describe,expect,it} from "vitest";
import {PlatformRegistry,normalizeOpportunity,estimateEconomics,evaluateOpportunity,selectModelTier} from "../commerce/index.js";
const registry=new PlatformRegistry();
const policy={minimumFitBps:7000,minimumExpectedProfitCents:2000,minimumExpectedValueCents:1000,maximumProposalCompetition:50,requirePaymentVerification:true,minimumTranslationConfidenceBps:7500};
const profile={skills:["excel","csv","automation","openclaw"],supportedLanguages:["en","es"],maximumDeliveryCostCents:20000};
function opportunity(p:Partial<Parameters<typeof normalizeOpportunity>[0]>={}){return normalizeOpportunity({platformId:"upwork",sourceId:"1",url:"https://example.test/job/1",language:"en",title:"Automate report",body:"Repeatable spreadsheet work",budgetCents:30000,currency:"USD",clientPaymentVerified:true,clientRatingBps:9000,proposalCount:5,requiredSkills:["excel","automation"],acceptanceCriteria:["sample output matches"],...p},{title:"Automate report",body:"Repeatable spreadsheet work",confidenceBps:9500});}
describe("global commerce engine",()=>{
 it("loads global and regional platforms",()=>{expect(registry.list().length).toBeGreaterThanOrEqual(15);expect(registry.get("workana").languages).toContain("es");expect(registry.get("lancers").languages).toContain("ja")});
 it("rejects duplicate platforms",()=>expect(()=>new PlatformRegistry([registry.get("upwork"),registry.get("upwork")])).toThrow(/duplicate/));
 it("normalizes immutable ids",()=>expect(opportunity().canonicalId).toBe("upwork:1"));
 it("rejects insecure URLs",()=>expect(()=>opportunity({url:"http://bad.test"})).toThrow(/HTTPS/));
 it("accounts for fees and reserves",()=>{const e=estimateEconomics(opportunity(),registry.get("upwork"),{acquisition:500,delivery:5000,model:1000,revisionBps:1000,refundBps:500},8000);expect(e.platformFeeCents).toBe(3000);expect(e.expectedNetProfitCents).toBe(16000);expect(e.expectedValueCents).toBe(12800)});
 it("proposes profitable high-fit work",()=>{const o=opportunity();const e=estimateEconomics(o,registry.get("upwork"),{acquisition:500,delivery:5000,model:1000,revisionBps:500,refundBps:500},8500);expect(evaluateOpportunity(o,registry.get("upwork"),profile,e,policy).decision).toBe("propose")});
 it("rejects unverified customers",()=>{const o=opportunity({clientPaymentVerified:false});const e=estimateEconomics(o,registry.get("upwork"),{acquisition:0,delivery:1,model:1,revisionBps:0,refundBps:0},9000);expect(evaluateOpportunity(o,registry.get("upwork"),profile,e,policy).reasons).toContain("PAYMENT_NOT_VERIFIED")});
 it("rejects saturated jobs",()=>{const o=opportunity({proposalCount:500});const e=estimateEconomics(o,registry.get("upwork"),{acquisition:0,delivery:1,model:1,revisionBps:0,refundBps:0},9000);expect(evaluateOpportunity(o,registry.get("upwork"),profile,e,policy).reasons).toContain("COMPETITION_TOO_HIGH")});
 it("reviews uncertain translations",()=>{const o={...opportunity(),translationConfidenceBps:5000};const e=estimateEconomics(o,registry.get("upwork"),{acquisition:0,delivery:1000,model:100,revisionBps:0,refundBps:0},9000);expect(evaluateOpportunity(o,registry.get("upwork"),profile,e,policy).decision).toBe("review")});
 it("rejects missing acceptance criteria",()=>{const o=opportunity({acceptanceCriteria:[]});const e=estimateEconomics(o,registry.get("upwork"),{acquisition:0,delivery:1,model:1,revisionBps:0,refundBps:0},9000);expect(evaluateOpportunity(o,registry.get("upwork"),profile,e,policy).reasons).toContain("ACCEPTANCE_CRITERIA_MISSING")});
 it("routes models by value and ambiguity",()=>{expect(selectModelTier({languageSupported:true,complexityBps:1000,ambiguityBps:1000,customerValueCents:1000})).toBe("cheap");expect(selectModelTier({languageSupported:false,complexityBps:1000,ambiguityBps:1000,customerValueCents:1000})).toBe("reasoning");expect(selectModelTier({languageSupported:true,complexityBps:4000,ambiguityBps:1000,customerValueCents:30000})).toBe("fast")});
});
