import {describe,expect,it} from "vitest";
import {createDeliveryManifest,deliveryAllowed,planFulfilment} from "../commerce/fulfilment-workflow.js";
const base:any={contractId:"contract-1",skillId:"software",scope:"Build a tested API integration with documented handover.",acceptance:["tests pass"],paymentVerified:true,customerFiles:["sample.json"],maximumRevisions:1};
describe("fulfilment workflow",()=>{
 it("creates an isolated quality-first plan after payment",()=>{const p=planFulfilment(base);expect(p.workspaceId).toBe("contract-contract-1");expect(p.steps).toContain("Run automated tests and static checks");expect(p.prohibitedActions).toContain("Modify the control-plane runtime");});
 it("blocks unpaid, vague, untestable, and path-traversal work",()=>{expect(()=>planFulfilment({...base,paymentVerified:false})).toThrow("PAYMENT_NOT_VERIFIED");expect(()=>planFulfilment({...base,scope:"do it"})).toThrow("SCOPE_INCOMPLETE");expect(()=>planFulfilment({...base,acceptance:[]})).toThrow("ACCEPTANCE_NOT_TESTABLE");expect(()=>planFulfilment({...base,customerFiles:["../secret"]})).toThrow("UNSAFE_FILENAME");});
 it("creates checksummed manifests only after all quality gates",()=>{const m=createDeliveryManifest({contractId:"contract-1",files:[{name:"result.txt",content:"done",mediaType:"text/plain"}],acceptanceResults:[{criterion:"tests pass",passed:true,evidence:"42 tests passed"}],qualityScoreBps:9800,paymentVerified:true,criticApproved:true});expect(m.files[0].sha256).toHaveLength(64);expect(deliveryAllowed(m)).toBe(true);});
 it("blocks failed acceptance, weak quality, missing critic, and empty delivery",()=>{const x:any={contractId:"x",files:[{name:"x.txt",content:"x",mediaType:"text/plain"}],acceptanceResults:[{criterion:"x",passed:true,evidence:"ok"}],qualityScoreBps:9800,paymentVerified:true,criticApproved:true};expect(()=>createDeliveryManifest({...x,qualityScoreBps:9499})).toThrow("QUALITY_GATE_FAILED");expect(()=>createDeliveryManifest({...x,criticApproved:false})).toThrow("CRITIC_NOT_APPROVED");expect(()=>createDeliveryManifest({...x,acceptanceResults:[{criterion:"x",passed:false,evidence:"failed"}]})).toThrow("ACCEPTANCE_FAILED");expect(()=>createDeliveryManifest({...x,files:[]})).toThrow("DELIVERABLE_EMPTY");});
});
