import {afterEach,describe,expect,it} from "vitest";import fs from "node:fs";import os from "node:os";import path from "node:path";
import {executeModelFulfilment,type ModelRunner} from "../commerce/model-fulfilment.js";
const roots:string[]=[];const input:any={contractId:"model-1",skillId:"research",scope:"Produce a concise evidence-separated research brief on a supplied synthetic market.",acceptance:["contains evidence section"],paymentVerified:true,customerFiles:[],maximumRevisions:1};
afterEach(()=>roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true})));
const runner=(outputs:string[]):ModelRunner=>({run:async()=>({content:outputs.shift()!,model:"test/model",inputTokens:10,outputTokens:20})});
describe("model fulfilment",()=>{
 it("writes output only after independent critic approval",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"model-"));roots.push(root);const r=await executeModelFulfilment(input,root,runner([JSON.stringify({files:[{name:"report.md",mediaType:"text/markdown",content:"# Evidence\nFixture"}],acceptanceResults:[{criterion:"x",passed:true,evidence:"section present"}],notes:"ok"}),JSON.stringify({approved:true,qualityScoreBps:9800,failures:[]})]));expect(r.model).toBe("test/model");expect(r.usage).toEqual({inputTokens:20,outputTokens:40});expect(fs.existsSync(path.join(r.workspacePath,"report.md"))).toBe(true);});
 it("blocks unsafe filenames",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"model-"));roots.push(root);await expect(executeModelFulfilment(input,root,runner([JSON.stringify({files:[{name:"../secret",content:"x"}],acceptanceResults:[{passed:true,evidence:"x"}]}),JSON.stringify({approved:true,qualityScoreBps:9800,failures:[]})]))).rejects.toThrow("MODEL_FILENAME_UNSAFE");});
 it("blocks critic rejection and weak quality",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"model-"));roots.push(root);const bundle=JSON.stringify({files:[{name:"x.md",content:"x"}],acceptanceResults:[{passed:true,evidence:"x"}]});await expect(executeModelFulfilment(input,root,runner([bundle,JSON.stringify({approved:false,qualityScoreBps:9000,failures:["weak"]})]))).rejects.toThrow("MODEL_CRITIC_REJECTED");});
});
