import {describe,expect,it,vi} from "vitest";
import {PlatformRegistry} from "../commerce/platform-registry.js";
import {UgigAdapter} from "../commerce/ugig-adapter.js";

describe("UGig adapter",()=>{
 it("discovers active gigs without credentials",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({gigs:[{id:"g1",title:"Build API automation",description:"Implement and test an API workflow",status:"active",budget_max:500,payment_coin:"USDC",listing_type:"hiring",skills_required:["typescript"],poster:{username:"buyer"}}]}),{status:200,headers:{"content-type":"application/json"}})) as any;const adapter=new UgigAdapter(new PlatformRegistry().get("ugig"),{},fetcher);expect((await adapter.health()).ready).toBe(true);const result=await adapter.discover();expect(result.opportunities[0]).toMatchObject({sourceId:"g1",budgetCents:50000,currency:"USDC"});});
 it("does not apply to gigs posted by its own profile",async()=>{let n=0;const fetcher=vi.fn(async()=>{n++;return n===1?new Response(JSON.stringify({gigs:[{id:"own",title:"Our listing",status:"active",budget_max:500,payment_coin:"USDC",poster:{id:"me",username:"oakhampton"}},{id:"other",title:"External API work",status:"active",budget_max:600,payment_coin:"USDC",poster:{id:"them",username:"buyer"}}]}),{status:200}):new Response(JSON.stringify({id:"me",username:"oakhampton"}),{status:200});}) as any;const adapter=new UgigAdapter(new PlatformRegistry().get("ugig"),{AUTOMATON_UGIG_API_KEY:"test"},fetcher);const result=await adapter.discover();expect(result.opportunities.map(x=>x.sourceId)).toEqual(["other"]);});
 it("maps notifications into commerce messages",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({notifications:[{id:"n1",type:"application_update",title:"Application accepted",body:"The client accepted your application",data:{gig_id:"g1"},created_at:"2026-07-22T01:00:00Z"}]}),{status:200,headers:{"content-type":"application/json"}})) as any;const adapter=new UgigAdapter(new PlatformRegistry().get("ugig"),{AUTOMATON_UGIG_API_KEY:"test",AUTOMATON_UGIG_EMAIL:"agent@example.com"},fetcher);const result=await adapter.fetchMessages();expect(result.messages[0]).toMatchObject({id:"n1",subject:"Application accepted",threadId:"g1"});}); it("requires a scoped key before submission",async()=>{const adapter=new UgigAdapter(new PlatformRegistry().get("ugig"),{});await expect(adapter.submitApprovedAction({type:"submit_proposal",payload:{proposal:{sourceId:"g1",body:"specific",priceCents:10000}},idempotencyKey:"one"})).rejects.toThrow("UGIG_API_KEY_MISSING");});
});
