import {SHADOW_OFFERS,renderOfferPage,type ShadowOffer} from "./offer-catalog.js";

const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export interface OfferSiteConfig{intakeUrl:string;campaignPrefix:string;contactEmail:string;}
export interface OfferSiteFile{path:string;content:string;}
export function renderOfferIntakePage(offer:ShadowOffer,config:OfferSiteConfig):string{
 const base=renderOfferPage(offer).replace("</body>","");
 const questions=offer.intakeQuestions.map((q,i)=>`<label>${escape(q)}<textarea name="q${i+1}" required maxlength="2000"></textarea></label>`).join("");
 return `${base}<section class="card"><h2>Request a scoped review</h2><form id="intake" method="post" action="${escape(config.intakeUrl)}"><input type="hidden" name="offerId" value="${escape(offer.offer.id)}"><input type="hidden" name="campaignId" value="${escape(config.campaignPrefix+offer.slug)}"><label>Email<input type="email" name="email" required autocomplete="email"></label>${questions}<label>Anything else we should know?<textarea name="problem" required minlength="10" maxlength="10000"></textarea></label><button type="submit">Request review</button></form><p><small>No payment is taken until scope, acceptance checks and delivery timing are confirmed. Contact: ${escape(config.contactEmail)}</small></p></section><p><a href="/automation-services/privacy.html">Privacy</a> Ãƒâ€šÃ‚Â· <a href="/automation-services/terms.html">Terms</a></p><div id="status" role="status"></div><script>document.getElementById("intake").addEventListener("submit",async function(e){e.preventDefault();const f=new FormData(this),details=[];for(const [k,v] of f.entries())if(k.startsWith("q"))details.push(String(v));const body={email:String(f.get("email")||""),problem:[...details,String(f.get("problem")||"")].filter(Boolean).join("\\n\\n"),offerId:String(f.get("offerId")||""),campaignId:String(f.get("campaignId")||""),language:"en"};const r=await fetch(this.action,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok)location.href="/automation-services/thank-you.html";else document.getElementById("status").textContent="Submission failed. Please email seth@oakhampton.ai.";});</script><style>form{display:grid;gap:14px}label{display:grid;gap:6px;font-weight:650}input,textarea{font:inherit;padding:12px;border:1px solid #9aa7b1;border-radius:8px}textarea{min-height:95px}</style></body></html>`;
}
export function buildOfferSite(config:OfferSiteConfig):OfferSiteFile[]{
 const cards=SHADOW_OFFERS.map(o=>`<article><h2>${escape(o.offer.title)}</h2><p>${escape(o.offer.promisedOutcome)}</p><p><strong>AUD $${(o.offer.priceCents/100).toFixed(0)}</strong> Ãƒâ€šÃ‚Â· ${o.deliveryDays} days</p><a href="${escape(o.slug)}/">View fixed scope</a></article>`).join("");
 const index=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Oakhampton practical automation services</title><style>body{font:18px system-ui;max-width:960px;margin:60px auto;padding:0 22px;color:#17202a}h1{font-size:48px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}article{border:1px solid #d8e0e5;border-radius:16px;padding:22px}a{color:#075985}</style></head><body><p>Oakhampton Ãƒâ€šÃ‚Â· Human-reviewed AI-assisted delivery</p><h1>Small, fixed-scope work delivered quickly and checked properly.</h1><main>${cards}</main><p><a href="/automation-services/privacy.html">Privacy</a> Ãƒâ€šÃ‚Â· <a href="/automation-services/terms.html">Terms</a></p></body></html>`;
 const privacy=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Privacy</title></head><body><main><h1>Privacy</h1><p>Submit only information needed to assess your request. Do not send passwords, private keys, full banking credentials or unredacted sensitive records through this form. Information is used to assess scope, communicate and deliver agreed work.</p><p>Contact ${escape(config.contactEmail)} for access or deletion requests.</p></main></body></html>`;
 const terms=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Terms</title></head><body><main><h1>Service terms</h1><p>Displayed prices are starting prices for the stated fixed scope. Work begins only after scope, acceptance checks, timing and payment terms are confirmed. One consolidated revision round is included unless agreed otherwise. Services do not provide tax, legal, medical or regulated financial advice.</p></main></body></html>`;
 const thanks=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Request received</title></head><body><main><h1>Request received</h1><p>We will review the scope and reply before any payment or work begins.</p><p><a href="./">Return to services</a></p></main></body></html>`;
 return[{path:"index.html",content:index},{path:"privacy.html",content:privacy},{path:"terms.html",content:terms},{path:"thank-you.html",content:thanks},...SHADOW_OFFERS.map(o=>({path:`${o.slug}/index.html`,content:renderOfferIntakePage(o,config)}))];
}
