import {estimateEconomics,evaluateOpportunity,normalizeOpportunity,type CapabilityProfile,type CommercePolicy} from "../commerce/engine.js";
import {PlatformRegistry} from "../commerce/platform-registry.js";
export interface ComplexWorkPiece { id:string;platformId:string;language:string;currency:string;budgetCents:number;skills:string[];criteria:string[];baseCosts:{acquisition:number;delivery:number;model:number;revisionBps:number;refundBps:number};baseSuccessBps:number;translationBps:number;proposalCount:number; }
export interface WorkPieceSpread { id:string;runs:number;propose:number;review:number;reject:number;expectedValue:{minimum:number;p10:number;median:number;p90:number;maximum:number;mean:number};netProfit:{minimum:number;median:number;maximum:number};topReasons:Array<[string,number]>;representative:{best:{decision:string;expectedValueCents:number};median:{decision:string;expectedValueCents:number};worst:{decision:string;expectedValueCents:number}}; }
export const COMPLEX_WORK_PIECES:ComplexWorkPiece[]=[
{id:"global-workbook-consolidation",platformId:"upwork",language:"en",currency:"USD",budgetCents:120000,skills:["excel","automation","data-validation"],criteria:["100 input files normalize","control totals reconcile","exception workbook produced","repeat run is idempotent"],baseCosts:{acquisition:2500,delivery:30000,model:5000,revisionBps:800,refundBps:500},baseSuccessBps:8200,translationBps:9800,proposalCount:18},
{id:"openclaw-vps-migration",platformId:"contra",language:"en",currency:"USD",budgetCents:250000,skills:["openclaw","docker","vps","monitoring"],criteria:["backup verified","staging migration passes","connectors recover","rollback tested"],baseCosts:{acquisition:1500,delivery:65000,model:12000,revisionBps:1200,refundBps:700},baseSuccessBps:7200,translationBps:9900,proposalCount:4},
{id:"spanish-proposal-invoice-automation",platformId:"workana",language:"es",currency:"USD",budgetCents:80000,skills:["workflow-automation","email-ops","document-generation"],criteria:["Spanish templates approved","invoice totals exact","follow-up suppression works"],baseCosts:{acquisition:1800,delivery:22000,model:6000,revisionBps:1000,refundBps:800},baseSuccessBps:7600,translationBps:8500,proposalCount:12},
{id:"algora-streaming-regression-bounty",platformId:"algora",language:"en",currency:"USD",budgetCents:150000,skills:["typescript","testing","api-debugging"],criteria:["bug reproduced","regression test fails before patch","full suite passes","maintainer merges PR"],baseCosts:{acquisition:1000,delivery:50000,model:14000,revisionBps:500,refundBps:300},baseSuccessBps:6100,translationBps:9900,proposalCount:0}];
class Rng{constructor(private s:number){}next(){this.s=(this.s*1103515245+12345)>>>0;return this.s/4294967296}range(a:number,b:number){return a+(b-a)*this.next()}}
const pct=(x:number[],p:number)=>x[Math.min(x.length-1,Math.max(0,Math.floor((x.length-1)*p)))];
export function simulateComplexWorkPiece(w:ComplexWorkPiece,runs:number,seed:number,profile:CapabilityProfile,policy:CommercePolicy,registry=new PlatformRegistry()):WorkPieceSpread{const rng=new Rng(seed),rows:Array<{decision:string;ev:number;net:number;reasons:string[]}>=[];for(let i=0;i<runs;i++){const budget=Math.round(w.budgetCents*rng.range(.7,1.25)),cost=(n:number)=>Math.max(0,Math.round(n*rng.range(.65,1.65))),confidence=Math.round(w.translationBps*rng.range(.72,1.04)),success=Math.min(10000,Math.round(w.baseSuccessBps*rng.range(.6,1.15)));const criteria=rng.next()<.04?[]:w.criteria,paid=rng.next()>=.03,proposals=Math.round(w.proposalCount*rng.range(.5,3));const o=normalizeOpportunity({platformId:w.platformId,sourceId:`${w.id}-${i}`,url:`https://example.test/${w.id}/${i}`,language:w.language,title:w.id,body:"Complex synthetic work piece",budgetCents:budget,currency:w.currency,clientPaymentVerified:paid,proposalCount:proposals,requiredSkills:w.skills,acceptanceCriteria:criteria},{title:w.id,body:"Translated complex work piece",confidenceBps:confidence});const e=estimateEconomics(o,registry.get(w.platformId),{acquisition:cost(w.baseCosts.acquisition),delivery:cost(w.baseCosts.delivery),model:cost(w.baseCosts.model),revisionBps:cost(w.baseCosts.revisionBps),refundBps:cost(w.baseCosts.refundBps)},success);const d=evaluateOpportunity(o,registry.get(w.platformId),profile,e,policy);rows.push({decision:d.decision,ev:e.expectedValueCents,net:e.expectedNetProfitCents,reasons:d.reasons})}const ev=rows.map(x=>x.ev).sort((a,b)=>a-b),net=rows.map(x=>x.net).sort((a,b)=>a-b),reason=new Map<string,number>();for(const x of rows)for(const r of x.reasons)reason.set(r,(reason.get(r)??0)+1);const sorted=[...rows].sort((a,b)=>a.ev-b.ev),view=(x:typeof rows[number])=>({decision:x.decision,expectedValueCents:x.ev});return{id:w.id,runs,propose:rows.filter(x=>x.decision==="propose").length,review:rows.filter(x=>x.decision==="review").length,reject:rows.filter(x=>x.decision==="reject").length,expectedValue:{minimum:ev[0],p10:pct(ev,.1),median:pct(ev,.5),p90:pct(ev,.9),maximum:ev.at(-1)!,mean:Math.round(ev.reduce((a,b)=>a+b,0)/runs)},netProfit:{minimum:net[0],median:pct(net,.5),maximum:net.at(-1)!},topReasons:[...reason.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5),representative:{worst:view(sorted[0]),median:view(sorted[Math.floor(runs/2)]),best:view(sorted.at(-1)!)}};}
export function runComplexPortfolio(runsPerPiece=1000,seed=20260720){const profile={skills:["excel","automation","data-validation","openclaw","docker","vps","monitoring","workflow-automation","email-ops","document-generation","typescript","testing","api-debugging"],supportedLanguages:["en","es"],maximumDeliveryCostCents:150000};const policy={minimumFitBps:7000,minimumExpectedProfitCents:10000,minimumExpectedValueCents:5000,maximumProposalCompetition:50,requirePaymentVerification:true,minimumTranslationConfidenceBps:7500};return COMPLEX_WORK_PIECES.map((w,i)=>simulateComplexWorkPiece(w,runsPerPiece,seed+i*997,profile,policy));}
