import type { GrowthPolicy,OfferHypothesis,PainSignal,WebsiteExperiment } from "../economic/growth-loop.js";
export const SAFE_GROWTH_POLICY:GrowthPolicy={minimumEvidenceQualityBps:6000,minimumIndependentSignals:2,minimumContributionMarginBps:3000,minimumPaidOrdersBeforeScale:3,maximumCustomerAcquisitionCostCents:3000,maximumExperimentLossCents:5000,minimumSettledProfitCentsToSpawn:10000,minimumQueueDepthToSpawn:5};
export const PAIN_SIGNALS:PainSignal[]=[
{id:"r1",channel:"reddit",sourceUrl:"https://reddit.com/r/example/1",capturedAt:"2026-07-20T00:00:00Z",text:"Weekly reconciliation takes hours",audience:"small agencies",frequency:12,urgencyBps:8000,willingnessToPayBps:7000,evidenceQualityBps:7000,termsPermitCommercialAnalysis:true,containsPersonalData:false},
{id:"f1",channel:"forum",sourceUrl:"https://example.test/forum/1",capturedAt:"2026-07-20T00:00:00Z",text:"Need reconciliation before month end",audience:"small agencies",frequency:7,urgencyBps:8500,willingnessToPayBps:7500,evidenceQualityBps:6500,termsPermitCommercialAnalysis:true,containsPersonalData:false},
{id:"private",channel:"reddit",sourceUrl:"https://reddit.com/r/example/2",capturedAt:"2026-07-20T00:00:00Z",text:"Includes customer identity",audience:"small agencies",frequency:1,urgencyBps:9999,willingnessToPayBps:9999,evidenceQualityBps:9999,termsPermitCommercialAnalysis:false,containsPersonalData:true}];
export const RECONCILIATION_OFFER:OfferHypothesis={id:"offer-reconcile",title:"48-hour reconciliation review",targetAudience:"small agencies",promisedOutcome:"Clean exception report and action list",priceCents:25000,deliveryCostCents:4000,modelCostCents:1200,supportReserveCents:1500,refundReserveBps:1000,evidenceSignalIds:["r1","f1"]};
const e=(id:string,p:Partial<WebsiteExperiment>):WebsiteExperiment=>({id,offerId:"offer-reconcile",host:"here.now",acquisitionChannel:"organic",trafficBudgetCents:0,visitors:0,qualifiedLeads:0,paidOrders:0,settledRevenueCents:0,refundsCents:0,chargebacksCents:0,deploymentApproved:true,advertisingApproved:false,...p});
export const GROWTH_SCENARIOS:Array<{id:string;experiment:WebsiteExperiment;queueDepth:number;expected:"stop"|"iterate"|"scale";spawn:boolean}>=[
{id:"zero-traffic",queueDepth:0,expected:"iterate",spawn:false,experiment:e("e0",{})},
{id:"profitable-low-volume",queueDepth:1,expected:"iterate",spawn:false,experiment:e("e1",{trafficBudgetCents:500,visitors:100,qualifiedLeads:8,paidOrders:2,settledRevenueCents:50000})},
{id:"paid-ads-unapproved",queueDepth:10,expected:"iterate",spawn:false,experiment:e("e2",{acquisitionChannel:"paid_ads",trafficBudgetCents:4000,visitors:300,qualifiedLeads:25,paidOrders:5,settledRevenueCents:125000})},
{id:"refund-collapse",queueDepth:10,expected:"stop",spawn:false,experiment:e("e3",{trafficBudgetCents:1000,visitors:100,qualifiedLeads:20,paidOrders:4,settledRevenueCents:25000,refundsCents:30000,chargebacksCents:5000})},
{id:"profitable-demand",queueDepth:8,expected:"scale",spawn:true,experiment:e("e4",{trafficBudgetCents:2500,visitors:500,qualifiedLeads:45,paidOrders:8,settledRevenueCents:200000})},
{id:"high-cac",queueDepth:9,expected:"iterate",spawn:false,experiment:e("e5",{acquisitionChannel:"paid_ads",trafficBudgetCents:20000,visitors:1000,qualifiedLeads:15,paidOrders:4,settledRevenueCents:100000,advertisingApproved:true})}];